version: "3"

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        image: php:7-fpm
        container_name: php
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
